name: bookollab
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flare_flutter: ^2.0.6
  flutter_svg: ^0.19.3
  introduction_screen: ^2.0.0
  firebase_auth: ^1.0.0
  pin_code_fields: ^7.0.0
  cloud_firestore: ^1.0.0
  barcode_scan: "^1.0.0"
  images_picker: ^1.0.0
  rflutter_alert:
    git: git://github.com/RatelHub/rflutter_alert.git
  flutter_barcode_scanner: ^1.0.2
  firebase_storage: ^8.0.1
  razorpay_flutter: 1.1.1
  dio: ^4.0.0
  flutter_dropdown: ^0.0.8
  fluttertoast: ^8.0.3
  jiffy: ^4.1.0
  toggle_switch: ^0.1.9
  font_awesome_flutter: ^9.0.0
  flutter_switch: ^0.3.1
  unicorndial: ^1.1.5
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.0.4
  webviewx: ^0.0.4
  getwidget: ^2.0.2
  intl: ^0.17.0
  awesome_notifications: ^0.0.6+7
  firebase_messaging: ^9.1.2
  flutter_local_notifications: ^6.0.0
  sweetsheet: ^0.2.0
  random_string: ^2.1.0
  sn_progress_dialog: ^1.0.1
  auto_size_text: ^2.1.0
  transparent_image: ^2.0.0
  flutter_image_compress: ^1.0.0
  path_provider: ^2.0.2
  pagination: ^0.1.0
  paginate_firestore: ^0.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - UIAssets/
    - UIAssets/LoginScreen/
    - UIAssets/Onboarding/UI1/
    - UIAssets/Onboarding/UI2/
    - UIAssets/Onboarding/UI3/
    - UIAssets/BookInfo/
    - UIAssets/Homepage/
    - UIAssets/Profile/
  fonts:
    - family: Avenir95Black
      fonts:
        - asset: assets/fonts/AvenirLTProBlack.otf
    - family: LeelawUI
      fonts:
        - asset: assets/fonts/LeelawUI.ttf
