class BookShort {
/*
{
  "id": 19,
  "available": 1,
  "book_title": "Chamber of Secrtes",
  "img_url": null,
  "tags": "thriller",
  "genre": "thriller"
} 
*/

  int id;
  int available;
  String bookTitle;
  String imgUrl;
  String tags;
  String genre;

  BookShort({
    this.id,
    this.available,
    this.bookTitle,
    this.imgUrl,
    this.tags,
    this.genre,
  });
  BookShort.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    available = json["available"]?.toInt();
    bookTitle = json["book_title"]?.toString();
    imgUrl = json["img_url"]?.toString();
    tags = json["tags"]?.toString();
    genre = json["genre"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["available"] = available;
    data["book_title"] = bookTitle;
    data["img_url"] = imgUrl;
    data["tags"] = tags;
    data["genre"] = genre;
    return data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BookDetailed {
/*
{
  "available": 1,
  "Condition_book": "new",
  "mrp": "440",
  "author": "J.K ROWLING",
  "book_title": "Chamber of Secrtes",
  "img_url": null,
  "tags": "thriller",
  "genre": "thriller"
} 
*/

  int available;
  String conditionBook;
  String mrp;
  String author;
  String bookTitle;
  String imgUrl;
  String tags;
  String genre;

  BookDetailed({
    this.available,
    this.conditionBook,
    this.mrp,
    this.author,
    this.bookTitle,
    this.imgUrl,
    this.tags,
    this.genre,
  });
  BookDetailed.fromJson(Map<String, dynamic> json) {
    available = json["available"]?.toInt();
    conditionBook = json["Condition_book"]?.toString();
    mrp = json["mrp"]?.toString();
    author = json["author"]?.toString();
    bookTitle = json["book_title"]?.toString();
    imgUrl = json["img_url"]?.toString();
    tags = json["tags"]?.toString();
    genre = json["genre"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["available"] = available;
    data["Condition_book"] = conditionBook;
    data["mrp"] = mrp;
    data["author"] = author;
    data["book_title"] = bookTitle;
    data["img_url"] = imgUrl;
    data["tags"] = tags;
    data["genre"] = genre;
    return data;
  }
}

