class BookShort {
/*
{
  "id": 19,
  "available": 1,
  "book_title": "Chamber of Secrtes",
  "img_url": null,
  "tags": "thriller",
  "genre": "thriller"
} 
*/

  int id;
  int available;
  String bookTitle;
  String imgUrl;
  String tags;
  String genre;

  BookShort({
    this.id,
    this.available,
    this.bookTitle,
    this.imgUrl,
    this.tags,
    this.genre,
  });
  BookShort.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    available = json["available"]?.toInt();
    bookTitle = json["book_title"]?.toString();
    imgUrl = json["img_url"]?.toString();
    tags = json["tags"]?.toString();
    genre = json["genre"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["available"] = available;
    data["book_title"] = bookTitle;
    data["img_url"] = imgUrl;
    data["tags"] = tags;
    data["genre"] = genre;
    return data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BookDetailed {
/*
{
  "available": 1,
  "Condition_book": "new",
  "mrp": "440",
  "author": "J.K ROWLING",
  "book_title": "Chamber of Secrtes",
  "img_url": null,
  "tags": "thriller",
  "genre": "thriller"
} 
*/

  int available;
  String conditionBook;
  String mrp;
  String author;
  String bookTitle;
  String imgUrl;
  String tags;
  String genre;

  BookDetailed({
    this.available,
    this.conditionBook,
    this.mrp,
    this.author,
    this.bookTitle,
    this.imgUrl,
    this.tags,
    this.genre,
  });
  BookDetailed.fromJson(Map<String, dynamic> json) {
    available = json["available"]?.toInt();
    conditionBook = json["Condition_book"]?.toString();
    mrp = json["mrp"]?.toString();
    author = json["author"]?.toString();
    bookTitle = json["book_title"]?.toString();
    imgUrl = json["img_url"]?.toString();
    tags = json["tags"]?.toString();
    genre = json["genre"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["available"] = available;
    data["Condition_book"] = conditionBook;
    data["mrp"] = mrp;
    data["author"] = author;
    data["book_title"] = bookTitle;
    data["img_url"] = imgUrl;
    data["tags"] = tags;
    data["genre"] = genre;
    return data;
  }
}

class AddBook {
/*
{
  "book_title": "Lord of Rings",
  "mrp": 600,
  "condition": "new",
  "isbn": "bcbcfckofnifkvrvkr",
  "author": "J. R. R. Tolkien",
  "gentags": "mystery",
  "tags": "action",
  "description": "A very nice booK"
} 
*/

  String bookTitle;
  int mrp;
  String condition;
  String isbn;
  String author;
  String gentags;
  String tags;
  String description;

  AddBook({
    this.bookTitle,
    this.mrp,
    this.condition,
    this.isbn,
    this.author,
    this.gentags,
    this.tags,
    this.description,
  });
  AddBook.fromJson(Map<String, dynamic> json) {
    bookTitle = json["book_title"]?.toString();
    mrp = json["mrp"]?.toInt();
    condition = json["condition"]?.toString();
    isbn = json["isbn"]?.toString();
    author = json["author"]?.toString();
    gentags = json["gentags"]?.toString();
    tags = json["tags"]?.toString();
    description = json["description"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["book_title"] = bookTitle;
    data["mrp"] = mrp;
    data["condition"] = condition;
    data["isbn"] = isbn;
    data["author"] = author;
    data["gentags"] = gentags;
    data["tags"] = tags;
    data["description"] = description;
    return data;
  }
}

