///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GenreList {
/*
{
  "id": 26,
  "owner_id": 2,
  "available": 0,
  "Condition_book": "new",
  "isbn_no": "bcbcfckofnifkvrvkr",
  "mrp": "600",
  "created_date": "2021-10-03 06:58:59",
  "is_approved": 1,
  "author": "J. R. R. Tolkien",
  "book_title": "Lord of Rings",
  "img_url": "",
  "description": "A very nice booK",
  "tags": "action",
  "genre": "mystery,thriller",
  "is_borrowed": 1,
  "lending_charge": 20,
  "location": "Bitha,Patna,Bihar,801106"
} 
*/

  int id;
  int ownerId;
  int available;
  String ConditionBook;
  String isbnNo;
  String mrp;
  String createdDate;
  int isApproved;
  String author;
  String bookTitle;
  String imgUrl;
  String description;
  String tags;
  String genre;
  int isBorrowed;
  int lendingCharge;
  String location;

  GenreList({
    this.id,
    this.ownerId,
    this.available,
    this.ConditionBook,
    this.isbnNo,
    this.mrp,
    this.createdDate,
    this.isApproved,
    this.author,
    this.bookTitle,
    this.imgUrl,
    this.description,
    this.tags,
    this.genre,
    this.isBorrowed,
    this.lendingCharge,
    this.location,
  });
  GenreList.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    ownerId = json["owner_id"]?.toInt();
    available = json["available"]?.toInt();
    ConditionBook = json["Condition_book"]?.toString();
    isbnNo = json["isbn_no"]?.toString();
    mrp = json["mrp"]?.toString();
    createdDate = json["created_date"]?.toString();
    isApproved = json["is_approved"]?.toInt();
    author = json["author"]?.toString();
    bookTitle = json["book_title"]?.toString();
    imgUrl = json["img_url"]?.toString();
    description = json["description"]?.toString();
    tags = json["tags"]?.toString();
    genre = json["genre"]?.toString();
    isBorrowed = json["is_borrowed"]?.toInt();
    lendingCharge = json["lending_charge"]?.toInt();
    location = json["location"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["owner_id"] = ownerId;
    data["available"] = available;
    data["Condition_book"] = ConditionBook;
    data["isbn_no"] = isbnNo;
    data["mrp"] = mrp;
    data["created_date"] = createdDate;
    data["is_approved"] = isApproved;
    data["author"] = author;
    data["book_title"] = bookTitle;
    data["img_url"] = imgUrl;
    data["description"] = description;
    data["tags"] = tags;
    data["genre"] = genre;
    data["is_borrowed"] = isBorrowed;
    data["lending_charge"] = lendingCharge;
    data["location"] = location;
    return data;
  }
}